<?php

namespace Proxies\__CG__\Eloboosted\GameinjectionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Compte extends \Eloboosted\GameinjectionBundle\Entity\Compte implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'idCompte', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'nom', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'prenom', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'dateDeNaissance', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'email', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'pseudo', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'motDePasse', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'etat', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'points', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'rank', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'image', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'nombreDeSignalisation', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'archive', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'telNum', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'admin'];
        }

        return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'idCompte', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'nom', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'prenom', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'dateDeNaissance', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'email', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'pseudo', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'motDePasse', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'etat', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'points', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'rank', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'image', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'nombreDeSignalisation', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'archive', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'telNum', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Compte' . "\0" . 'admin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Compte $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCompte()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCompte();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCompte', []);

        return parent::getIdCompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCompte($idCompte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCompte', [$idCompte]);

        return parent::setIdCompte($idCompte);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', []);

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance($dateDeNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', [$dateDeNaissance]);

        return parent::setDateDeNaissance($dateDeNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPseudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPseudo', []);

        return parent::getPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPseudo($pseudo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPseudo', [$pseudo]);

        return parent::setPseudo($pseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotDePasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotDePasse', []);

        return parent::getMotDePasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotDePasse($motDePasse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotDePasse', [$motDePasse]);

        return parent::setMotDePasse($motDePasse);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoints', []);

        return parent::getPoints();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoints($points)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoints', [$points]);

        return parent::setPoints($points);
    }

    /**
     * {@inheritDoc}
     */
    public function getRank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRank', []);

        return parent::getRank();
    }

    /**
     * {@inheritDoc}
     */
    public function setRank($rank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRank', [$rank]);

        return parent::setRank($rank);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreDeSignalisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreDeSignalisation', []);

        return parent::getNombreDeSignalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreDeSignalisation($nombreDeSignalisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreDeSignalisation', [$nombreDeSignalisation]);

        return parent::setNombreDeSignalisation($nombreDeSignalisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchive', []);

        return parent::getArchive();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchive($archive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchive', [$archive]);

        return parent::setArchive($archive);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelNum', []);

        return parent::getTelNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelNum($telNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelNum', [$telNum]);

        return parent::setTelNum($telNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin', []);

        return parent::getAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin($admin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin', [$admin]);

        return parent::setAdmin($admin);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

}
