eloboosted_backoffice_homepage:
    path:     /
    defaults: { _controller: EloboostedBackofficeBundle:Default:index }

eloboosted_backoffice_tournoi:
    path:     /Tournaments
    defaults: { _controller: EloboostedBackofficeBundle:Tournoi:index }

eloboosted_backoffice_updatetournoi:
    path:     /updatet
    defaults: { _controller: EloboostedBackofficeBundle:Tournoi:up}
eloboosted_backoffice_tournoi_show:
    path:     /{id}/showTournament
    defaults: { _controller: EloboostedBackofficeBundle:Tournoi:show }
    methods:  GET

eloboosted_backoffice_tournoi_new:
    path:     /newTournament
    defaults: { _controller: "EloboostedBackofficeBundle:Tournoi:new" }
    methods:  [GET, POST]

eloboosted_backoffice_tournoi_edit:
    path:     /{id}/editTournament
    defaults: { _controller: "EloboostedBackofficeBundle:Tournoi:edit" }
    methods:  [GET, POST]

eloboosted_backoffice_tournoi_delete:
    path:     /{id}/deleteTournament
    defaults: { _controller: "EloboostedBacktofficeBundle:Tournoi:delete" }
    methods:  [GET, POST]

AccountReports:
    path:     /AccountReports
    defaults: { _controller: EloboostedBackofficeBundle:Compte:AccountReports }

WarnTarget:
    path:     /WarnTarget
    defaults: { _controller: EloboostedBackofficeBundle:Signalisation:WarnTarget }

WarnSender:
    path:     /WarnSender
    defaults: { _controller: EloboostedBackofficeBundle:Signalisation:WarnSender }
eloboosted_backoffice_games:
    path:     /games
    defaults: { _controller: EloboostedBackofficeBundle:Games:index }

addcategorypost:
    path:     /addcategorypost
    defaults: { _controller: EloboostedBackofficeBundle:Post:addcategorypost }


#taha routes

tcategorie_index:
    path:     /cat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:index" }
    methods:  GET

tcategorie_show:
    path:     /{id}/showcat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:show" }
    methods:  GET

tcategorie_new:
    path:     /newcat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:new" }
    methods:  [GET, POST]

tcategorie_edit:
    path:     /{id}/editcat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:edit" }
    methods:  [GET, POST]

tcategorie_delete:
    path:     /{id}/deletecat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:delete" }
    methods:  DELETE

tevenement_index:
    path:     /events
    defaults: { _controller: "EloboostedBackofficeBundle:TEvenement:index" }
    methods:  GET

tevenement_new:
    path:     /newevent
    defaults: { _controller: "EloboostedBackofficeBundle:TEvenement:new" }
    methods:  [GET, POST]

tevenement_edit:
    path:     /{id}/editevent
    defaults: { _controller: "EloboostedBackofficeBundle:TEvenement:edit" }
    methods:  [GET, POST]

tevenement_delete:
    path:     /{id}/deleteevent
    defaults: { _controller: "EloboostedBackofficeBundle:TEvenement:delete" }
    methods:  DELETE
eloboosted_gamelist_index:
    path:     /gamelist
    defaults: { _controller: EloboostedBackofficeBundle:Gamelist:index }

eloboosted_gamelist_new:
    path:     /gamelistnew
    defaults: { _controller: EloboostedBackofficeBundle:Gamelist:newGamelist }
eloboosted_gamelist_delete:
    path:     /gamelistdel/{id}
    defaults: { _controller: EloboostedBackofficeBundle:Gamelist:delete }

eloboosted_backoffice_NewGame:
    path:     /NewGame
    defaults: { _controller: EloboostedBackofficeBundle:Games:NewGame }

eloboosted_backoffice_DeleteGame:
    path:     /DeleteGame/{id}
    defaults: { _controller: EloboostedBackofficeBundle:Games:DeleteGame }

eloboosted_backoffice_EditGame:
    path:     /{id}/EditGame
    defaults: { _controller: EloboostedBackofficeBundle:Games:EditGame }
    methods:  [GET, POST]

eloboosted_backoffice_addCathegorie:
    path:     /addCathegorie
    defaults: { _controller: EloboostedBackofficeBundle:Cathegorie:addCathegorie }

eloboosted_backoffice_cathegorieList:
    path:     /cathegorieList
    defaults: { _controller: EloboostedBackofficeBundle:Cathegorie:cathegorieList }

eloboosted_backoffice_deleteCath:
    path:     /deleteCath/{id}
    defaults: { _controller: EloboostedBackofficeBundle:Cathegorie:deleteCath }

eloboosted_backoffice_EditCath:
    path:     /EditCath/{id}
    defaults: { _controller: EloboostedBackofficeBundle:Cathegorie:EditCath }

eloboosted_backoffice_accepted:
    path:     /accepted/{id}
    defaults: { _controller: EloboostedBackofficeBundle:Games:accecpted }

