eloboosted_backoffice_homepage:
    path:     /
    defaults: { _controller: EloboostedBackofficeBundle:Default:index }

eloboosted_backoffice_tournoi:
    path:     /Tournaments
    defaults: { _controller: EloboostedBackofficeBundle:Tournoi:index }

AccountReports:
    path:     /AccountReports
    defaults: { _controller: EloboostedBackofficeBundle:Compte:AccountReports }

WarnTarget:
    path:     /WarnTarget
    defaults: { _controller: EloboostedBackofficeBundle:Signalisation:WarnTarget }

WarnSender:
    path:     /WarnSender
    defaults: { _controller: EloboostedBackofficeBundle:Signalisation:WarnSender }
eloboosted_backoffice_games:
    path:     /games
    defaults: { _controller: EloboostedBackofficeBundle:Games:index }
