eloboosted_backoffice_homepage:
    path:     /
    defaults: { _controller: EloboostedBackofficeBundle:Default:index }

eloboosted_backoffice_tournoi:
    path:     /Tournaments
    defaults: { _controller: EloboostedBackofficeBundle:Tournoi:index }

eloboosted_backoffice_updatetournoi:
    path:     /updatet
    defaults: { _controller: EloboostedBackofficeBundle:Tournoi:up}
eloboosted_backoffice_tournoi_show:
    path:     /{id}/showTournament
    defaults: { _controller: EloboostedBackofficeBundle:Tournoi:show }
    methods:  GET

eloboosted_backoffice_tournoi_new:
    path:     /newTournament
    defaults: { _controller: "EloboostedBackofficeBundle:Tournoi:new" }
    methods:  [GET, POST]

eloboosted_backoffice_tournoi_edit:
    path:     /{id}/editTournament
    defaults: { _controller: "EloboostedBackofficeBundle:Tournoi:edit" }
    methods:  [GET, POST]

eloboosted_backoffice_tournoi_delete:
    path:     /{id}/deleteTournament
    defaults: { _controller: "EloboostedBacktofficeBundle:Tournoi:delete" }
    methods:  DELETE

AccountReports:
    path:     /AccountReports
    defaults: { _controller: EloboostedBackofficeBundle:Compte:AccountReports }

WarnTarget:
    path:     /WarnTarget
    defaults: { _controller: EloboostedBackofficeBundle:Signalisation:WarnTarget }

WarnSender:
    path:     /WarnSender
    defaults: { _controller: EloboostedBackofficeBundle:Signalisation:WarnSender }
eloboosted_backoffice_games:
    path:     /games
    defaults: { _controller: EloboostedBackofficeBundle:Games:index }

addcategorypost:
    path:     /addcategorypost
    defaults: { _controller: EloboostedBackofficeBundle:Post:addcategorypost }


#taha routes

tcategorie_index:
    path:     /cat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:index" }
    methods:  GET

tcategorie_show:
    path:     /{id}/showcat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:show" }
    methods:  GET

tcategorie_new:
    path:     /newcat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:new" }
    methods:  [GET, POST]

tcategorie_edit:
    path:     /{id}/editcat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:edit" }
    methods:  [GET, POST]

tcategorie_delete:
    path:     /{id}/deletecat
    defaults: { _controller: "EloboostedBackofficeBundle:TCategorie:delete" }
    methods:  DELETE

tevenement_index:
    path:     /events
    defaults: { _controller: "EloboostedBackofficeBundle:TEvenement:index" }
    methods:  GET

tevenement_new:
    path:     /newevent
    defaults: { _controller: "EloboostedBackofficeBundle:TEvenement:new" }
    methods:  [GET, POST]

tevenement_edit:
    path:     /{id}/editevent
    defaults: { _controller: "EloboostedBackofficeBundle:TEvenement:edit" }
    methods:  [GET, POST]

tevenement_delete:
    path:     /{id}/deleteevent
    defaults: { _controller: "EloboostedBackofficeBundle:TEvenement:delete" }
    methods:  DELETE
