AddProduct_page:
    path:     /addProd
    defaults: { _controller: EloboostedFrontofficeBundle:Products:AddProduct }
frontoffice_index:
    path:     /
    defaults: { _controller: EloboostedFrontofficeBundle:Default:index }
    methods:  GET
tournoi_index:
    path:     /Tournaments/{p}
    defaults:  { _controller:   EloboostedFrontofficeBundle:Tournoi:index , p: 1 }
tournoi_show:
    path:     /{id}/showTournament
    defaults: { _controller: EloboostedFrontofficeBundle:Tournoi:show }
    methods:  GET

tournoi_new:
    path:     /newTournament
    defaults: { _controller: EloboostedFrontofficeBundle:Tournoi:new }
    methods:  [GET, POST]

tournoi_edit:
    path:     /{id}/editTournament
    defaults: { _controller: "EloboostedFrontofficeBundle:Tournoi:edit" }
    methods:  [GET, POST]

tournoi_delete:
    path:     /{id}/deleteTournament
    defaults: { _controller: "EloboostedFrontofficeBundle:Tournoi:delete" }
    methods:  DELETE
trournoi_commentaire_new:
    path:     /{tournoi}/newcommenttr
    defaults: { _controller: "EloboostedFrontofficeBundle:TournamentsComments:New" }
get_user_img:
    path:     /image/{id}
    defaults: { _controller: EloboostedFrontofficeBundle:Images:img }
home:
    path:     /home
    defaults: { _controller: EloboostedFrontofficeBundle:Default:index }
AddPost:
    path:     /addPost
    defaults: { _controller: EloboostedFrontofficeBundle:Post:addPost}
showAllPosts:
    path:     /showAllPosts
    defaults: { _controller: EloboostedFrontofficeBundle:Post:showAllPosts}
readPost:
    path:     /readPost
    defaults: { _controller: EloboostedFrontofficeBundle:Post:readPost}
removePost:
    path:     /removePost
    defaults: { _controller: EloboostedFrontofficeBundle:Post:removePost}
like:
    path:     /like
    defaults: { _controller: EloboostedFrontofficeBundle:Post:like}
commentaire:
    path:     /commentaire/{id}
    defaults: { _controller: EloboostedFrontofficeBundle:Post:commentaire}
Addcommentaire:
    path:     /Addcommentaire/{id}
    defaults: { _controller: EloboostedFrontofficeBundle:Post:Addcommentaire}