AddProduct_page:
    path:     /addProd
    defaults: { _controller: EloboostedFrontofficeBundle:Products:AddProduct }
frontoffice_index:
    path:     /
    defaults: { _controller: EloboostedFrontofficeBundle:Default:index }
    methods:  GET
tournoi_index:
    path:     /Tournaments/{p}
    defaults:  { _controller:   EloboostedFrontofficeBundle:Tournoi:index , p: 1 }
tournoi_show:
    path:     /{id}/showTournament
    defaults: { _controller: EloboostedFrontofficeBundle:Tournoi:show }
    methods:  GET

tournoi_new:
    path:     /newTournament
    defaults: { _controller: EloboostedFrontofficeBundle:Tournoi:new }
    methods:  [GET, POST]

tournoi_edit:
    path:     /{id}/editTournament
    defaults: { _controller: "EloboostedFrontofficeBundle:Tournoi:edit" }
    methods:  [GET, POST]

tournoi_delete:
    path:     /{id}/deleteTournament
    defaults: { _controller: "EloboostedFrontofficeBundle:Tournoi:delete" }
    methods:  DELETE
trournoi_commentaire_new:
    path:     /{tournoi}/newcommenttr
    defaults: { _controller: "EloboostedFrontofficeBundle:TournamentsComments:New" }
get_user_img:
    path:     /image/{id}
    defaults: { _controller: EloboostedFrontofficeBundle:Images:img }
home:
    path:     /home
    defaults: { _controller: EloboostedFrontofficeBundle:Default:index }
AddPost:
    path:     /addPost
    defaults: { _controller: EloboostedFrontofficeBundle:Post:addPost}
showAllPosts:
    path:     /showAllPosts
    defaults: { _controller: EloboostedFrontofficeBundle:Post:showAllPosts}
readPost:
    path:     /readPost
    defaults: { _controller: EloboostedFrontofficeBundle:Post:readPost}
removePost:
    path:     /removePost
    defaults: { _controller: EloboostedFrontofficeBundle:Post:removePost}
like:
    path:     /like/{id}/{post}
    defaults: { _controller: EloboostedFrontofficeBundle:Post:like}
commentaire:
    path:     /commentaire/{id}
    defaults: { _controller: EloboostedFrontofficeBundle:Post:commentaire}
Addcommentaire:
    path:     /Addcommentaire
    defaults: { _controller: EloboostedFrontofficeBundle:Post:Addcommentaire}
report:
    path:     /report/{id}
    defaults: { _controller: EloboostedFrontofficeBundle:Post:report}
reportcomment:
    path:     /reportcomment/{id}
    defaults: { _controller: EloboostedFrontofficeBundle:Post:reportcomment}
myProfile:
    path: /myProfile
    defaults: { _controller:  EloboostedFrontofficeBundle:Compte:myProfile }
createAccount:
    path:     /createAccount
    defaults: { _controller: EloboostedFrontofficeBundle:Compte:createAccount}

accountcreation:
    path:     /accountcreation
    defaults: { _controller: EloboostedFrontofficeBundle:Compte:accountcreation}
lstnots:
    path: /lstNot
    defaults: { _controller:  EloboostedFrontofficeBundle:Notification:NotificationlistRender }

SendMail:
    path: /SendMail
    defaults: { _controller:  EloboostedFrontofficeBundle:Compte:sendMail }

SendInvite:
    path: /SendInvite
    defaults: { _controller:  EloboostedFrontofficeBundle:Compte:SendInvite }
acceptInvFromNot:
    path: /acceptInvFromNot
    defaults: { _controller:  EloboostedFrontofficeBundle:Notification:acceptInvFromNot }
RefuseInvFromNot:
    path: /RefuseInvFromNot
    defaults: { _controller:  EloboostedFrontofficeBundle:Notification:RefuseInvFromNot }

myProfile:
    path: /myProfile
    defaults: { _controller:  EloboostedFrontofficeBundle:Compte:myProfile }
userProfile:
    path: /userProfile/{id}
    defaults: { _controller:  EloboostedFrontofficeBundle:Compte:userProfile }
yes_index:
    path:     /games
    defaults: { _controller: "EloboostedFrontofficeBundle:Games:index" }
    methods:  GET

yes_show:
    path:     /{id}/showGames
    defaults: { _controller: "EloboostedFrontofficeBundle:Games:show" }
    methods:  GET

yes_new:
    path:     /newGames
    defaults: { _controller: "EloboostedFrontofficeBundle:Games:new" }
    methods:  [GET, POST]

yes_edit:
    path:     /{id}/editGames
    defaults: { _controller: "EloboostedFrontofficeBundle:Games:edit" }
    methods:  [GET, POST]

yes_delete:
    path:     /{id}/deleteGames
    defaults: { _controller: "EloboostedFrontofficeBundle:Games:delete" }
    methods:  DELETE

Search_tournament:
    path:     /Searchtournament
    defaults: { _controller: EloboostedFrontofficeBundle:Tournoi:serachtournament }

participation_new:
    path:     /Participate/{tournament}
    defaults: { _controller: EloboostedFrontofficeBundle:Participation:newParticipation }