eloboosted_frontoffice_homepage:
    path:     /addTournament
    defaults: { _controller: EloboostedFrontofficeBundle:Tournament:add }
AddProduct_page:
    path:     /addProd
    defaults: { _controller: EloboostedFrontofficeBundle:Products:AddProduct }
