<?php

namespace Proxies\__CG__\Eloboosted\GameinjectionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ChatLog extends \Eloboosted\GameinjectionBundle\Entity\ChatLog implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'idChatMessage', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'idCompte1', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'idCompte2', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'time', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'content'];
        }

        return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'idChatMessage', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'idCompte1', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'idCompte2', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'time', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\ChatLog' . "\0" . 'content'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ChatLog $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdChatMessage()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdChatMessage();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdChatMessage', []);

        return parent::getIdChatMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdChatMessage($idChatMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdChatMessage', [$idChatMessage]);

        return parent::setIdChatMessage($idChatMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCompte1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCompte1', []);

        return parent::getIdCompte1();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCompte1($idCompte1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCompte1', [$idCompte1]);

        return parent::setIdCompte1($idCompte1);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCompte2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCompte2', []);

        return parent::getIdCompte2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCompte2($idCompte2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCompte2', [$idCompte2]);

        return parent::setIdCompte2($idCompte2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTime', []);

        return parent::getTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setTime($time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTime', [$time]);

        return parent::setTime($time);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

}
