<?php

namespace Proxies\__CG__\Eloboosted\GameinjectionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Games extends \Eloboosted\GameinjectionBundle\Entity\Games implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'idGames', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'nomGames', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'imageGames', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'prix', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'supported', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'description', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'idCathegorieg'];
        }

        return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'idGames', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'nomGames', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'imageGames', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'prix', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'supported', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'description', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Games' . "\0" . 'idCathegorieg'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Games $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdGames()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdGames();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGames', []);

        return parent::getIdGames();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGames($idGames)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGames', [$idGames]);

        return parent::setIdGames($idGames);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomGames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomGames', []);

        return parent::getNomGames();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomGames($nomGames)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomGames', [$nomGames]);

        return parent::setNomGames($nomGames);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageGames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageGames', []);

        return parent::getImageGames();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageGames($imageGames)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageGames', [$imageGames]);

        return parent::setImageGames($imageGames);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupported()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupported', []);

        return parent::getSupported();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupported($supported)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupported', [$supported]);

        return parent::setSupported($supported);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCathegorieg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCathegorieg', []);

        return parent::getIdCathegorieg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCathegorieg($idCathegorieg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCathegorieg', [$idCathegorieg]);

        return parent::setIdCathegorieg($idCathegorieg);
    }

}
