<?php

namespace Proxies\__CG__\Eloboosted\GameinjectionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Signalisation extends \Eloboosted\GameinjectionBundle\Entity\Signalisation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Signalisation' . "\0" . 'idSignalisation', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Signalisation' . "\0" . 'idCommentaireSng', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Signalisation' . "\0" . 'idPostSng', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Signalisation' . "\0" . 'idCompteSng'];
        }

        return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Signalisation' . "\0" . 'idSignalisation', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Signalisation' . "\0" . 'idCommentaireSng', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Signalisation' . "\0" . 'idPostSng', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Signalisation' . "\0" . 'idCompteSng'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Signalisation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdSignalisation()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdSignalisation();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSignalisation', []);

        return parent::getIdSignalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSignalisation($idSignalisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSignalisation', [$idSignalisation]);

        return parent::setIdSignalisation($idSignalisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCommentaireSng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCommentaireSng', []);

        return parent::getIdCommentaireSng();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCommentaireSng($idCommentaireSng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCommentaireSng', [$idCommentaireSng]);

        return parent::setIdCommentaireSng($idCommentaireSng);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPostSng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPostSng', []);

        return parent::getIdPostSng();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPostSng($idPostSng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPostSng', [$idPostSng]);

        return parent::setIdPostSng($idPostSng);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCompteSng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCompteSng', []);

        return parent::getIdCompteSng();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCompteSng($idCompteSng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCompteSng', [$idCompteSng]);

        return parent::setIdCompteSng($idCompteSng);
    }

}
