<?php

namespace Proxies\__CG__\Eloboosted\GameinjectionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tournoi extends \Eloboosted\GameinjectionBundle\Entity\Tournoi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'idTournoi', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'nom', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'startDate', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'endDate', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'reward1', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'reward2', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'reward3', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'prixParJoueur', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'nbrJoueur', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'etat', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'imageTournoi', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'idCompteTrn', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'idGameTrn'];
        }

        return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'idTournoi', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'nom', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'startDate', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'endDate', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'reward1', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'reward2', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'reward3', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'prixParJoueur', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'nbrJoueur', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'etat', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'imageTournoi', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'idCompteTrn', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\Tournoi' . "\0" . 'idGameTrn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tournoi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdTournoi()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdTournoi();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTournoi', []);

        return parent::getIdTournoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTournoi($idTournoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTournoi', [$idTournoi]);

        return parent::setIdTournoi($idTournoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate(\DateTime $startDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$startDate]);

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', []);

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate($endDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', [$endDate]);

        return parent::setEndDate($endDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getReward1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReward1', []);

        return parent::getReward1();
    }

    /**
     * {@inheritDoc}
     */
    public function setReward1($reward1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReward1', [$reward1]);

        return parent::setReward1($reward1);
    }

    /**
     * {@inheritDoc}
     */
    public function getReward2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReward2', []);

        return parent::getReward2();
    }

    /**
     * {@inheritDoc}
     */
    public function setReward2($reward2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReward2', [$reward2]);

        return parent::setReward2($reward2);
    }

    /**
     * {@inheritDoc}
     */
    public function getReward3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReward3', []);

        return parent::getReward3();
    }

    /**
     * {@inheritDoc}
     */
    public function setReward3($reward3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReward3', [$reward3]);

        return parent::setReward3($reward3);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixParJoueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixParJoueur', []);

        return parent::getPrixParJoueur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixParJoueur($prixParJoueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixParJoueur', [$prixParJoueur]);

        return parent::setPrixParJoueur($prixParJoueur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrJoueur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrJoueur', []);

        return parent::getNbrJoueur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrJoueur($nbrJoueur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrJoueur', [$nbrJoueur]);

        return parent::setNbrJoueur($nbrJoueur);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageTournoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageTournoi', []);

        return parent::getImageTournoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageTournoi($imageTournoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageTournoi', [$imageTournoi]);

        return parent::setImageTournoi($imageTournoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCompteTrn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCompteTrn', []);

        return parent::getIdCompteTrn();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCompteTrn($idCompteTrn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCompteTrn', [$idCompteTrn]);

        return parent::setIdCompteTrn($idCompteTrn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGameTrn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGameTrn', []);

        return parent::getIdGameTrn();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGameTrn($idGameTrn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGameTrn', [$idGameTrn]);

        return parent::setIdGameTrn($idGameTrn);
    }

}
