<?php

namespace Proxies\__CG__\Eloboosted\GameinjectionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JeuPost extends \Eloboosted\GameinjectionBundle\Entity\JeuPost implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'idGame', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'nom', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'description', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'image', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'supporter', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'idCathegorieJp'];
        }

        return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'idGame', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'nom', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'description', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'image', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'supporter', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\JeuPost' . "\0" . 'idCathegorieJp'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (JeuPost $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdGame()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdGame();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGame', []);

        return parent::getIdGame();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGame($idGame)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGame', [$idGame]);

        return parent::setIdGame($idGame);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupporter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupporter', []);

        return parent::getSupporter();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupporter($supporter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupporter', [$supporter]);

        return parent::setSupporter($supporter);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCathegorieJp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCathegorieJp', []);

        return parent::getIdCathegorieJp();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCathegorieJp($idCathegorieJp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCathegorieJp', [$idCathegorieJp]);

        return parent::setIdCathegorieJp($idCathegorieJp);
    }

}
