<?php

namespace Proxies\__CG__\Eloboosted\GameinjectionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TProduit extends \Eloboosted\GameinjectionBundle\Entity\TProduit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'idProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'libelleProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'descriptionProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'marqueProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'prixProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'dateProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'etat', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'imgProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'imageProduit2', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'imageProduit3', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'idCompteProd', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'idCategorieProd'];
        }

        return ['__isInitialized__', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'idProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'libelleProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'descriptionProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'marqueProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'prixProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'dateProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'etat', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'imgProduit', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'imageProduit2', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'imageProduit3', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'idCompteProd', '' . "\0" . 'Eloboosted\\GameinjectionBundle\\Entity\\TProduit' . "\0" . 'idCategorieProd'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TProduit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProduit()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProduit();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduit', []);

        return parent::getIdProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProduit($idProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProduit', [$idProduit]);

        return parent::setIdProduit($idProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleProduit', []);

        return parent::getLibelleProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleProduit($libelleProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleProduit', [$libelleProduit]);

        return parent::setLibelleProduit($libelleProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionProduit', []);

        return parent::getDescriptionProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionProduit($descriptionProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionProduit', [$descriptionProduit]);

        return parent::setDescriptionProduit($descriptionProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarqueProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarqueProduit', []);

        return parent::getMarqueProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarqueProduit($marqueProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarqueProduit', [$marqueProduit]);

        return parent::setMarqueProduit($marqueProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixProduit', []);

        return parent::getPrixProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixProduit($prixProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixProduit', [$prixProduit]);

        return parent::setPrixProduit($prixProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateProduit', []);

        return parent::getDateProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateProduit($dateProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateProduit', [$dateProduit]);

        return parent::setDateProduit($dateProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgProduit', []);

        return parent::getImgProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgProduit($imgProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgProduit', [$imgProduit]);

        return parent::setImgProduit($imgProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageProduit2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageProduit2', []);

        return parent::getImageProduit2();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageProduit2($imageProduit2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageProduit2', [$imageProduit2]);

        return parent::setImageProduit2($imageProduit2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageProduit3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageProduit3', []);

        return parent::getImageProduit3();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageProduit3($imageProduit3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageProduit3', [$imageProduit3]);

        return parent::setImageProduit3($imageProduit3);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCompteProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCompteProd', []);

        return parent::getIdCompteProd();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCompteProd($idCompteProd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCompteProd', [$idCompteProd]);

        return parent::setIdCompteProd($idCompteProd);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategorieProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategorieProd', []);

        return parent::getIdCategorieProd();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategorieProd($idCategorieProd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategorieProd', [$idCategorieProd]);

        return parent::setIdCategorieProd($idCategorieProd);
    }

}
